fileserver.c: include stdio.h (required for snprintf)
fileserver.c:44:9: warning: implicit declaration of function 'snprintf' [-Wimplicit-function-declaration]
   44 |         snprintf(final_filename, 1024, "%s/%s", fs->server_name, filename);
      |         ^~~~~~~~